@startuml

title __CLASES's Class Diagram__\n

skinparam classAttributeIconSize 0

      class Administrador {
      }
  
      class Aplicacion {
          {static} + minApoyos : int
          - bloqueados : List<Ciudadano>
          - elemCol : List<ElementoColectivo>
          - proyectos : List<Proyecto>
          + addBloqueado(ciudadano: Ciudadano): boolean
          + addElemCol(elemCol: ElementoColectivo): boolean
          + addProyecto(proyecto: Proyecto): boolean
          + cargar(path: String): Aplicacion
          + findCiudadano(username: String): Ciudadano
          + findColectivo(nombre: String): Colectivo
          + findProyecto(id: int): Proyecto
          + generarInformeAfinidad(c1: Colectivo, c2: Colectivo): double
          + guardar(path: String)
          + notificarNuevoProyecto(p: Proyecto)
          + notificarRegistro(c: Ciudadano)
          + removeBloqueado(ciudadano: Ciudadano): boolean
          + removeElemCol(elemCol: ElementoColectivo): boolean
          + removeProyecto(p: Proyecto): boolean
      }
  

    class Ciudadano {
      - admitido : boolean
      - bloqueado : boolean
      - colectivos : Set<Colectivo>
      - colectivosRepresentados : List<Colectivo>
      - nif : String
      - proyectos : Set<Proyecto>
      - proyectosApoyados : Set<Proyecto>
      + addColectivo(colectivo: Colectivo): boolean
      + addColectivoRepresentado(colectivo: Colectivo): boolean
      + addProyecto(proyecto: Proyecto): boolean
      + addProyectoApoyado(proyecto: Proyecto): boolean
      + admitir()
      + bloquear()
      + desbloquear()
      + removeColectivo(colectivo: Colectivo): boolean
      + removeColectivoRepresentado(colectivo: Colectivo): boolean
      + removeProyecto(proyecto: Proyecto): boolean
      + removeProyectoApoyado(proyecto: Proyecto): boolean
    }

      class Colectivo {
          - elementos : Set<ElementoColectivo>
          - nombre : String
          - proyectos : Set<Proyecto>
          - proyectosApoyados : Set<Proyecto>
          + addElemento(ciudadano: Ciudadano): boolean
          + addElemento(colectivo: Colectivo): boolean
          + addProyecto(proyecto: Proyecto): boolean
          + addProyectoApoyado(proyecto: Proyecto): boolean
          + removeElemento(elemento: ElementoColectivo): boolean
          + removeProyecto(proyecto: Proyecto): boolean
          + removeProyectoApoyado(proyecto: Proyecto): boolean
          - perteneceHijos(ciudadano: Ciudadano): boolean
      }

      enum Distrito {
        Arganzuela
        Barajas
        Carabanchel
        Centro
        Chamartin
        Chamberi
        CiudadLineal
        FuencarralElPardo
        Hortaleza
        Latina
        MoncloaAravaca
        Moratalaz
        PuenteDeVallecas
        Retiro
        Salamanca
        SanBlasCanillejas
        Tetuan
        Usera
        Vicalvaro
        VillaDeVallecas
        Villaverde
      }
  

      interface ElementoColectivo {
          {abstract} + addProyecto(proyecto: Proyecto): boolean
          {abstract} + addProyectoApoyado(proyecto: Proyecto): boolean
          {abstract} + removeProyecto(proyecto: Proyecto): boolean
          {abstract} + removeProyectoApoyado(proyecto: Proyecto): boolean
      }

      enum EstadoProyecto {
        ACEPTADO
        DENEGADO
        ENVIADO
        FINANCIADO
        INICIAL
        LISTOENVAR
        RECHAZADO
      }

      abstract class Notificacion {
          {abstract} + descripcion(): String
      }

      class NotificacionProy {
          + descripcion(): String
      }

      class NotificacionReg {
          + descripcion(): String
      }

      class Persistencia {
          - aplicacionMinApoyos : int
          - proyectoNextId : int
          + setValues()
      }

      abstract class Proyecto {
          - caducado : boolean
          - descripcion : String
          - fechaCreacion : Date
          - id : int
          - idEnvio : String
          - importeConcedido : double
          - importeSolicitado : double
          - nApoyos : int
          {static} - nextId : int
          - promotores : Set<ElementoColectivo>
          - suscriptores : Set<Ciudadano>
          - titulo : String
          - ultimoApoyo : Date
          + aceptar()
          + bloquearApoyo(c: Ciudadano): boolean
          + caducar()
          + consultarFinanciacion()
          + denegarFinanciacion()
          + enviarFinanciacion()
          + generarInformePopularidad(): int
          + notificarCambio()
          + rechazar()
          + recibirApoyo(ec: ElementoColectivo)
          + recibirApoyo(ec: ElementoColectivo, directo: boolean)
          {abstract} # crearSolicitud(): GrantRequest
          - recibirApoyo(c: Ciudadano)
          - recibirApoyo(c: Colectivo)
      }

      class ProyectoInfraestructura {
          - afectados : List<Distrito>
          - imagen : String
          + addAfectados(d: Distrito): boolean
          + removeAfectados(d: Distrito): boolean
          # crearSolicitud(): GrantRequest
      }

      class ProyectoSocial {
          - grupoSocial : String
          - nacional : boolean
          # crearSolicitud(): GrantRequest
      }

      abstract class SolicitudFinanciacion {
          + SolicitudFinanciacion()
          + getProject(): Proyecto
          + getProjectDescription(): String
          + getProjectTitle(): String
          + getRequestedAmount(): double
      }

      class SolicitudInfraestructura {
          + getExtraData(): String
          + getProjectKind(): ProjectKind
      }

      class SolicitudSocial {
          + getExtraData(): String
          + getProjectKind(): ProjectKind
      }

      abstract class Usuario {
          - password : String
          - pendientes : ArrayList<Notificacion>
          - username : String
      }
  

  Administrador -up-|> Usuario
  Aplicacion o-- Administrador : admin
  Aplicacion o-- Usuario : usuarioAcutal
  Aplicacion o-- Persistencia : varStatic
  Ciudadano .up.|> ElementoColectivo
  Ciudadano -up-|> Usuario
  Colectivo .up.|> ElementoColectivo
  Colectivo o-- Colectivo : padre
  Colectivo o-left- Ciudadano : representante
  NotificacionProy -left-|> Notificacion
  NotificacionProy o-right- Proyecto : sujeto
  NotificacionReg -left-|> Notificacion
  NotificacionReg o-- Ciudadano : sujeto
  Proyecto o-- EstadoProyecto : estado
  Proyecto o-- ElementoColectivo : propulsor
  ProyectoInfraestructura -up-|> Proyecto
  ProyectoSocial -up-|> Proyecto
  SolicitudFinanciacion .up.|> GrantRequest
  SolicitudFinanciacion o-left- Proyecto : p
  SolicitudInfraestructura -up-|> SolicitudFinanciacion
  SolicitudSocial -up-|> SolicitudFinanciacion


@enduml
